### ISSUE TITLE
模块引入错误

### ISSUE THREAD

**Issue by zactony** [wwayne/minii#15]
小程序基础库：2.8.0
本地调试没有问题，上传到线上就显示 Error: module 'store/minii.js' is not defined，这个是什么问题呢？

**Comment by wwayne** [comment]
看这个我判断不出，因为`store/minii.js`并不是属于这个lib的文件吧，你是有一个文件是`store/minii.js`吗？可以看看那个文件，会不会上传时被ignore了

**Comment by zactony** [comment]
我换了一个账号重新发布就有用了，目前我先关闭issue找原因吧
