### ISSUE TITLE
store的数据怎么分发到组件

### ISSUE THREAD

**Issue by wufangbing** [wwayne/minii#18]
现在store的数据可以和页面绑定并且分发到页面，但是不能分发到组件里面。

**Comment by wwayne** [comment]
恩目前是不能放到组件的 因为在小程序中 我希望组件使用时所有属性都是通过外层传入进来 而不应该和状态管理库结合在一起

**Comment by wufangbing** [comment]
原来是设计就是这样的，非常感谢

**Comment by wwayne** [comment]
恩不会 :)
