### ISSUE TITLE
store数据不能实时更新

### ISSUE THREAD

**Issue by wufangbing** [wwayne/minii#19]
在页面中更新store的数据之后，立即获取更新之后的值，获取不到最新的值。

例：
Page({
    test() {
        user.update({ name: 'zzz' });
        conso.log(this.data.name)  // 获取到的是上一个值
    }
})

**Comment by wwayne** [comment]
你有做这一步吗 [将状态和页面绑定起来](https://github.com/wwayne/minii#2-%E5%B0%86%E7%8A%B6%E6%80%81%E5%92%8C%E9%A1%B5%E9%9D%A2%E8%81%94%E7%B3%BB%E8%B5%B7%E6%9D%A5)
你也可以贴一下更完整的代码我帮你看下

**Comment by wufangbing** [comment]
// user.js
import { observe } from 'minii';
class UserInfo {
  name = 'wfb';
  updateName(name) {
    this.name = name;
  }
}
export default observe(new UserInfo(), 'user')

// index.js
import { mapToData } from 'minii'
import user from '../../stores/user.js'
const connect = mapToData((state) => ({
  name: state.user.name
}));

Page(connect({
  onLoad() {
    console.log(this.data.name);
    console.log('----------');
  },
  changeName() {
    user.updateName('zzz');
    console.log(this.data.name);
  }
}));

**Comment by wufangbing** [comment]
// user.js 文件
import { observe } from 'minii';
class UserInfo {
  name = 'wfb';
  updateName(name) {
    this.name = name;
  }
}
export default observe(new UserInfo(), 'user')


// index.js 文件
import { mapToData } from 'minii'
import user from '../../stores/user.js'
const connect = mapToData((state) => ({
  name: state.user.name
}));

Page(connect({
  onLoad() {
    console.log(this.data.name);  // 输出wfb
    console.log('----------'); 
    user.updateName('zzz');   
    console.log(this.data.name);  // 还是输出wfb
  }
}));

**Comment by wwayne** [comment]
这个库最后的行为其实就是调用了小程序的setData从而更新页面的数据，所以如果按你所示的来解释就相当于是在一个onLoad中先读取data，然后setData，再调用之前的data引用，它指向的还是旧的data

我个人觉得大多数时候不会有这样使用的情况，这个库本质还是利用proxy去调用小程序的setData从而让你页面的数据可以被及时的刷新
