### ISSUE TITLE
数据没办法实时更新？

### ISSUE THREAD

**Issue by hzp1993** [wwayne/minii#41]
app.js  执行 store 中的user.getUserInfo()
class UserStore{
  constructor() {
  userInfo: []
  }
  
  getUserInfo(){
    user.getUser().then(res => {
    this.userInfo = res.data
    }
  }
  
  export default observe(new UserStore(), 'users')
}

const connect = mapToData(function (state, opt) {
  console.log(state.users) // 这种情况打印出来是有数据
  console.log(state.users.userInfo)  返回来是[]空数组
})

**Comment by wwayne** [comment]
请问你是说 console.log(state.users) 这里userInfo是有数据的array，但是单独打印state.users.userInfo是空数组？
