### ISSUE TITLE
原生小程序里面不支持Proxy，用Proxy没问题吗？

### ISSUE THREAD

**Issue by shaobeichen** [wwayne/minii#8]
[客户端 ES6 API 支持情况 ](http://t.cn/AiNEMd06)

**Comment by wwayne** [comment]
@LeachZhou 从已经发布的两个小程序来看，目前还没有发现不支持的机型，但我只能说大部分机型目前看都没有问题吧，毕竟支持情况这个还是官方说了算，只是它这个文档目前看是不准确的。
